#pragma once

#define DIFFUSE_TEXTURE_SLOT 0
#define SPECULAR_TEXTURE_SLOT 1
#define EMISSION_TEXTURE_SLOT 2
#define NORMAL_TEXTURE_SLOT 3
// +4 reserved

#define DIR_SHADOWMAP_TEXTURE_SLOT 9
#define OMNI_SHADOWMAP_TEXTURE_SLOT 10
#define SKY_CUBEMAP_SLOT 11